name: reminder_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  table_calendar:
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  intl: ^0.20.2
  http: ^1.2.0
  image_picker: ^1.2.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4
  local_auth: ^2.2.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter:

  
  uses-material-design: true

  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/transparent-logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/transparent-logo.png"
